services:
  lixi_app:
    image: lixi-lixi_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lixi_app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3012:3000"
    volumes:
      - ./data:/app/data
      - ./public/banks:/app/public/banks
